const Images = {
  main_logo: require("../../assets/images/logo/main_logo.png"),
  ellipes_blur: require("../../assets/images/ellipes/blur.png"),
  checkedBox: require("../../assets/images/checkbox/checkbox_checked.png"),
  checkingBox: require("../../assets/images/checkbox/checkbox_uncheck.png"),
  backButton: require('../../assets/images/button/backbutton.png'),
  keyButton: require('../../assets/images/button/keybutton.png'),
  ellipes_blurhomepage: require('../../assets/images/ellipes/blur_homepage.png'),
  verifyMainImage: require('../../assets/images/button/verifymain.png'),
  cameraImage: require('../../assets/images/button/camera.png'),
  microphoneImage: require('../../assets/images/button/microphone.png'),
  locationImage: require('../../assets/images/button/location.png'),
  forwardImage: require('../../assets/images/button/forward.png'),
  sideBarImage: require('../../assets/images/logo/sidebarImage.png'),
  sideBarLogoImage: require('../../assets/images/logo/sidebarLogo.png'),
  ellipes_blurActivity: require('../../assets/images/ellipes/blur_activity.png'),
  ellipes_startMainImage: require('../../assets/images/ellipes/start_main.png'),
  deleteImage: require('../../assets/images/button/delete.png'),
  notificationImage: require('../../assets/images/button/notifications.png'),
  vibrationImage: require('../../assets/images/button/vibration.png'),
  mainSettingImage: require('../../assets/images/button/setting.png'),
  mainShareImage: require('../../assets/images/button/share.png'),
  mainPolicyImage: require('../../assets/images/button/policy.png'),
  mainStarImage: require('../../assets/images/button/star.png'),
  mainCloseImage: require('../../assets/images/button/close.png'),
  activityCallImage: require('../../assets/images/activity/call.png'),
  activityCameraImage: require('../../assets/images/activity/camera.png'),
  activityDeleteImage: require('../../assets/images/activity/delete.png'),
  activityFacebookImage: require('../../assets/images/activity/facebook.png'),
  activityGoogleCameraImage: require('../../assets/images/activity/googleCamera.png'),
  activityInstagramImage: require('../../assets/images/activity/instagram.png'),
  activityLocationImage: require('../../assets/images/activity/location.png'),
  activityMicImage: require('../../assets/images/activity/mic.png'),
  activityWarningImage: require('../../assets/images/activity/warning.png'),
  activityWhatsappImage: require('../../assets/images/activity/whatsapp.png'),
}

export default Images;